<?php

require_once(dirname(__FILE__) . '/../../../config.php');
require_once($CFG->libdir . '/adminlib.php');

$strheading = 'Element Library: Notifications';
$url = new moodle_url('/admin/tool/elementlibrary/notifications.php');

// Start setting up the page
$params = array();
$PAGE->set_context(get_system_context());
$PAGE->set_url($url);
$PAGE->set_title($strheading);
$PAGE->set_heading($strheading);

admin_externalpage_setup('toolelementlibrary');

echo $OUTPUT->header();

echo html_writer::link(new moodle_url('/admin/tool/elementlibrary/'), '&laquo; Back to index');
echo $OUTPUT->heading($strheading);


echo $OUTPUT->notification('This is an error notification <a href="#">with a link</a>');

echo $OUTPUT->notification('This is a success notification <a href="#">with a link</a>', 'notifysuccess');

echo $OUTPUT->notification('This is a standard notification <a href="#">with a link</a>', 'notifymessage');

echo $OUTPUT->notification('This is a redirect message notification. It looks like it\'s supposed to be used on a blank page as it has 10% top margin', 'redirectmessage');

echo $OUTPUT->error_text('This is an error generated using error_text(). I think this is used in form validation errors.');

echo $OUTPUT->box('This is a notice box <a href="#">with a link</a>, generated via box() with "generalbox" and "notice" classes added. Used by moodle in various places.', array('generalbox', 'notice'));

echo $OUTPUT->confirm('This is a confirmation box <a href="#">with a link</a>, generated by confirm(). It has the "box" and "generalbox" styles applied, as well as an id of "notice"', new moodle_url('notifications.php'), new moodle_url('notifications.php'));

echo $OUTPUT->footer();
